#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Functions
if [[ "$OSTYPE" == darwin* ]]; then
  function school {
    cdls "$HOME/Documents/School/Spring_18/$1"*
  }

  function filemerge {
    /Applications/Xcode.app/Contents/Applications/FileMerge.app/Contents/MacOS/FileMerge -left $1 -right $2
  }
fi

# Ignore spaced lines
HIST_IGNORE_SPACE="YES"
